modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/GaoXanSheng/CraftBrowser/issues"
license = "MIT"

[[mods]]
modId = "craftbrowser"
version = "${version}"
displayName = "Craftbrowser"
authors = "GaoXuShenG"
description = ''''''
logoFile = "icon.png"

[[dependencies.craftbrowser]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.craftbrowser]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.craftbrowser]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
